/**
 * Publishing module — UI strings (Bahasa Indonesia).
 * Nav keys live in src/i18n/id.ts (t.nav.publish/calendar/posts/media/compose);
 * everything else for this module lives here so parallel agents don't collide.
 */
export const p = {
  eyebrow: "Publikasi",
  calendarTitle: "Kalender konten",
  calendarSubtitle: "Rencanakan, setujui, dan jadwalkan post untuk semua akun klien.",
  postsTitle: "Semua post",
  postsSubtitle: "Semua post yang dibuat di aplikasi — dari draf sampai terbit.",
  mediaTitle: "Pustaka media",
  mediaSubtitle: "Gambar dan video yang siap dipakai di post.",
  composeTitle: "Buat post",
  composeSubtitle: "Satu caption, banyak akun — sesuaikan per platform bila perlu.",
  editTitle: "Ubah post",
  detailEyebrow: "Detail post",
  demoBanner:
    "Kredensial Meta belum diatur — publikasi dijalankan lewat simulasi (tidak ada yang benar-benar terkirim).",

  // ── status ────────────────────────────────────────────────
  status: {
    DRAFT: "Draf",
    IN_REVIEW: "Menunggu review",
    APPROVED: "Disetujui",
    SCHEDULED: "Terjadwal",
    PUBLISHING: "Sedang terbit",
    PUBLISHED: "Terbit",
    FAILED: "Gagal",
    REJECTED: "Ditolak",
  } as const,
  legend: "Legenda status",

  // ── calendar ──────────────────────────────────────────────
  month: "Bulan",
  week: "Minggu",
  today: "Hari ini",
  prev: "Sebelumnya",
  next: "Berikutnya",
  more: (n: number) => `+${n} lagi`,
  noPostsDay: "Tidak ada post di hari ini.",
  noPostsWeek: "Tidak ada post minggu ini.",
  allPlatforms: "Semua platform",
  allStatuses: "Semua status",
  dragHint: "Seret chip ke hari lain untuk mengubah jadwal.",
  rescheduled: "Jadwal diperbarui",
  timezoneNote: (tz: string) => `Waktu ditampilkan dalam zona klien (${tz}).`,
  statScheduled7d: "Terjadwal 7 hari ke depan",
  statInReview: "Menunggu review",
  statPublished30d: "Terbit 30 hari terakhir",
  statFailed: "Gagal",
  statDrafts: "Draf",
  scrollMetricsHint: "Geser untuk melihat metrik lainnya",

  // ── posts list ────────────────────────────────────────────
  colPost: "Post",
  colSchedule: "Jadwal",
  colTargets: "Akun",
  colStatus: "Status",
  colAuthor: "Penulis",
  colUpdated: "Diperbarui",
  searchPosts: "Cari judul atau caption…",
  untitled: "(tanpa judul)",
  noPosts: "Belum ada post",
  noPostsDesc: "Buat post pertama untuk klien ini — draf bisa disimpan kapan saja.",
  planned: "Rencana",

  // ── composer ──────────────────────────────────────────────
  sectionTargets: "Akun tujuan",
  sectionCaption: "Caption",
  sectionMedia: "Media",
  sectionLink: "Tautan & UTM",
  sectionExtras: "Lainnya",
  sectionSchedule: "Jadwal",
  sectionPreview: "Pratinjau",
  targetsHint: "Hanya akun milik klien yang bisa dipilih.",
  noAccounts: "Belum ada akun sosial milik klien. Tambahkan lewat Pengaturan Klien.",
  titleLabel: "Judul internal",
  titlePlaceholder: "mis. Promo akhir pekan — September",
  captionPlaceholder: "Tulis caption utama di sini…",
  chars: "karakter",
  hashtags: "hashtag",
  overrideFor: (platform: string) => `Caption khusus ${platform}`,
  overridePlaceholder: "Kosongkan untuk memakai caption utama",
  useMaster: "Pakai caption utama",
  pickFromLibrary: "Pilih dari pustaka",
  upload: "Unggah",
  uploading: "Mengunggah…",
  uploadHint: "JPG, PNG, WebP, GIF, MP4, MOV · maks. 25 MB per file",
  noMediaSelected: "Belum ada media. Instagram & TikTok membutuhkan media.",
  altText: "Teks alternatif",
  altPlaceholder: "Deskripsikan gambar untuk aksesibilitas",
  moveUp: "Geser ke atas",
  moveDown: "Geser ke bawah",
  remove: "Hapus",
  librarySearch: "Cari nama file atau tag…",
  libraryEmpty: "Pustaka masih kosong. Unggah media lebih dulu.",
  selectMedia: "Pilih media",
  selected: (n: number) => `${n} dipilih`,
  done: "Selesai",
  linkLabel: "Tautan",
  linkPlaceholder: "https://…",
  utmSource: "utm_source",
  utmMedium: "utm_medium",
  utmCampaign: "utm_campaign",
  utmPreview: "URL akhir",
  utmHint: "Parameter UTM ditambahkan ke tautan saat post terbit.",
  firstComment: "Komentar pertama (Instagram)",
  firstCommentPlaceholder: "Hashtag atau CTA yang dikirim sebagai komentar pertama",
  labels: "Label",
  labelsPlaceholder: "Tambah label lalu Enter",
  scheduleDate: "Tanggal",
  scheduleTime: "Jam",
  bestTimes: "Waktu terbaik",
  bestTimesHint: "Dari riwayat engagement akun klien.",
  bestTimesDefault: "Belum ada riwayat — memakai saran umum.",
  noSchedule: "Belum dijadwalkan",
  clearSchedule: "Kosongkan jadwal",
  saveDraft: "Simpan draf",
  saveChanges: "Simpan perubahan",
  saveAndSubmit: "Simpan & kirim review",
  saving: "Menyimpan…",
  savedDraft: "Draf tersimpan",
  savedChanges: "Perubahan tersimpan",
  editResetsNote: "Menyimpan perubahan akan mengembalikan post ke status Draf.",
  previewEmpty: "Pratinjau muncul setelah Anda memilih akun dan menulis caption.",
  previewSponsored: "Baru saja",
  previewLikes: "Disukai oleh 1.234 orang",
  previewSeeMore: "… selengkapnya",
  viewerReadOnly: "Anda hanya punya akses lihat untuk klien ini.",
  cannotEditStatus: "Post dengan status ini tidak bisa diubah. Batalkan jadwal atau duplikat post.",

  // ── detail ────────────────────────────────────────────────
  targets: "Akun tujuan",
  timeline: "Riwayat aktivitas",
  comments: "Komentar internal",
  commentPlaceholder: "Tulis catatan untuk tim…",
  send: "Kirim",
  noComments: "Belum ada komentar.",
  openPermalink: "Buka post",
  attempts: (n: number) => `${n}× percobaan`,
  author: "Penulis",
  approver: "Disetujui oleh",
  reviewNote: "Catatan review",
  scheduledFor: "Terjadwal",
  publishedAt: "Terbit",
  labelsEmpty: "Tanpa label",
  linkOut: "Tautan",

  // ── actions ───────────────────────────────────────────────
  act: {
    edit: "Ubah",
    submit: "Kirim untuk review",
    approve: "Setujui",
    reject: "Tolak",
    schedule: "Jadwalkan",
    unschedule: "Batalkan jadwal",
    publishNow: "Terbitkan sekarang",
    retry: "Coba lagi",
    duplicate: "Duplikat",
    delete: "Hapus",
    withdraw: "Tarik dari review",
    revise: "Revisi",
    backToDraft: "Kembalikan ke draf",
  },
  rejectTitle: "Tolak post",
  rejectDesc: "Beri alasan singkat agar penulis tahu apa yang perlu diperbaiki.",
  rejectPlaceholder: "mis. Ganti visual utama, caption terlalu panjang",
  scheduleTitle: "Jadwalkan post",
  scheduleDesc: "Pilih tanggal & jam terbit dalam zona waktu klien.",
  deleteTitle: "Hapus post?",
  deleteDesc: "Post, target, dan riwayatnya akan dihapus permanen.",
  publishNowTitle: "Terbitkan sekarang?",
  publishNowDesc: "Post akan langsung dikirim ke semua akun tujuan.",
  selfApprove: "Penyetuju harus orang lain (kecuali Admin).",

  // toasts
  toast: {
    submitted: "Post dikirim untuk review",
    approved: "Post disetujui",
    rejected: "Post ditolak",
    scheduled: "Post dijadwalkan",
    unscheduled: "Jadwal dibatalkan",
    published: "Post berhasil terbit",
    publishFailed: "Sebagian target gagal terbit",
    duplicated: "Post diduplikasi",
    deleted: "Post dihapus",
    commentAdded: "Komentar ditambahkan",
    retrying: "Mencoba ulang…",
    mediaUploaded: (n: number) => `${n} media diunggah`,
    mediaAdded: "Media ditambahkan",
    mediaUpdated: "Media diperbarui",
    mediaDeleted: "Media dihapus",
  },

  // ── media library ─────────────────────────────────────────
  kindAll: "Semua",
  kindImage: "Gambar",
  kindVideo: "Video",
  addByUrl: "Tambah dari URL",
  addByUrlDesc: "Tempel URL https gambar atau video yang bisa diakses publik.",
  urlLabel: "URL",
  kindLabel: "Jenis",
  tags: "Tag",
  tagsPlaceholder: "promo, produk, bts",
  usedIn: (n: number) => (n === 0 ? "Belum dipakai" : `Dipakai di ${n} post`),
  mediaInUse: "Media masih dipakai oleh post. Lepaskan dari post terlebih dahulu.",
  mediaEmpty: "Pustaka masih kosong",
  mediaEmptyDesc: "Unggah gambar/video atau tambahkan dari URL.",
  editMedia: "Ubah media",
  fileTooLarge: "Ukuran file melebihi 25 MB.",
  fileTypeNotAllowed: "Jenis file tidak didukung.",
  invalidHttpsUrl: "URL harus diawali https://",

  // activity timeline
  activity: {
    CREATED: "Post dibuat",
    EDITED: "Post diubah",
    SUBMITTED: "Dikirim untuk review",
    APPROVED: "Disetujui",
    REJECTED: "Ditolak",
    SCHEDULED: "Dijadwalkan",
    UNSCHEDULED: "Jadwal dibatalkan",
    RESCHEDULED: "Jadwal diubah",
    BACK_TO_DRAFT: "Dikembalikan ke draf",
    PUBLISHED: "Terbit",
    PUBLISH_FAILED: "Publikasi gagal",
    PUBLISH_RETRY: "Publikasi sebagian, akan dicoba ulang",
  } as Record<string, string>,
  system: "Sistem",
  simulated: "simulasi",
  editing: "Mode ubah",
  backToDetail: "Kembali ke detail",
  overrideBadge: "caption khusus",
  metaTitle: "Rincian",
  noLink: "Tanpa tautan",

  // notifications
  notif: {
    review: (title: string) => `Post menunggu review: ${title}`,
    reviewBody: "Buka untuk menyetujui atau menolak.",
    approved: (title: string) => `Post disetujui: ${title}`,
    rejected: (title: string) => `Post ditolak: ${title}`,
    published: (title: string) => `Post terbit: ${title}`,
    failed: (title: string) => `Post gagal terbit: ${title}`,
  },

  // errors
  err: {
    notFound: "Post tidak ditemukan.",
    transition: "Aksi tidak diizinkan untuk status post saat ini.",
    accountNotOwn: "Salah satu akun bukan milik klien ini.",
    mediaNotOwn: "Salah satu media bukan milik klien ini.",
    fixIssues: "Perbaiki dulu isu berikut:",
    noFailedTargets: "Tidak ada target yang gagal.",
    nothingToPublish: "Tidak ada target untuk diterbitkan.",
  },
} as const;
