/**
 * SEO suite — UI strings (Bahasa Indonesia). Shared keys live in src/i18n/id.ts
 * (t.common / t.seo / t.nav); this file holds everything specific to the suite so
 * parallel agents never touch id.ts.
 */
export const s = {
  demoBanner: "Menampilkan data demo SEO suite. Isi DATAFORSEO_LOGIN/PASSWORD untuk data nyata.",
  apifyBanner: "Posisi SERP nyata via Apify Google Search Scraper; volume, KD, dan backlink masih data demo sampai DataForSEO diisi.",
  refreshNow: "Perbarui sekarang",
  refreshing: "Memperbarui…",
  refreshCooldown: "Pembaruan berikutnya dapat dijalankan ±10 menit setelah pembaruan terakhir.",
  refreshThrottled: "Pembaruan terakhir kurang dari 10 menit lalu. Coba lagi beberapa menit.",
  unauthorized: "Anda tidak punya akses ke klien ini.",
  noProperty: "Properti SEO tidak ditemukan.",
  lastUpdated: "Diperbarui",
  viewer: "Hanya peran ADMIN/MANAGER yang dapat mengubah.",

  // ── Riset kata kunci ───────────────────────────────────────
  researchSubtitle: "Temukan ide kata kunci, volume, kesulitan & intent",
  seedLabel: "Kata kunci awal",
  seedPlaceholder: "mis. kopi susu gula aren",
  searchIdeas: "Cari ide",
  modeIdeas: "Ide",
  modeQuestions: "Pertanyaan",
  modeRelated: "Terkait",
  researchEmptyTitle: "Mulai dari satu kata kunci",
  researchEmptyDesc: "Masukkan kata kunci awal — kami turunkan ratusan ide beserta volume, kesulitan (KD), CPC, intent, dan fitur SERP.",
  researchNoResults: "Tidak ada ide untuk kata kunci ini.",
  cachedAt: "Hasil dari cache",
  cacheNote: "Hasil disimpan 7 hari agar tidak memanggil API berulang.",
  ideas: "Ide",
  totalVolume: "Total volume",
  avgKd: "Rata-rata KD",
  volume: "Volume",
  volumeHint: "Perkiraan pencarian per bulan (Google, Indonesia).",
  trend12: "Tren 12 bln",
  kd: "KD",
  kdHint: "Keyword Difficulty 0–100: seberapa sulit masuk 10 besar. <30 mudah · 30–59 sedang · 60–79 sulit · ≥80 sangat sulit.",
  cpc: "CPC",
  intent: "Intent",
  serpFeatures: "Fitur SERP",
  minVolume: "Volume min.",
  maxKd: "KD maks.",
  includeWords: "Mengandung kata",
  excludeWords: "Tanpa kata",
  anyIntent: "Semua intent",
  filterPlaceholderInclude: "mis. harga",
  filterPlaceholderExclude: "mis. gratis",
  selected: "dipilih",
  trackSelected: "Lacak",
  tracked: "Dilacak",
  trackedAdded: "kata kunci ditambahkan ke pelacak peringkat",
  trackedNone: "Semua kata kunci terpilih sudah dilacak.",
  selectAllVisible: "Pilih semua yang tampil",
  clearSelection: "Batal pilih",
  bandEasy: "Mudah",
  bandMedium: "Sedang",
  bandHard: "Sulit",
  bandVeryHard: "Sangat sulit",
  intentInformational: "Informasi",
  intentNavigational: "Navigasi",
  intentCommercial: "Komersial",
  intentTransactional: "Transaksi",

  // ── Kesenjangan kata kunci ─────────────────────────────────
  gapTitle: "Kesenjangan kata kunci",
  gapDesc: "Bandingkan kata kunci organik domain Anda dengan satu kompetitor.",
  gapPickCompetitor: "Pilih kompetitor",
  gapNoCompetitors: "Belum ada kompetitor domain. Tambahkan di halaman Kompetitor Domain.",
  gapManageCompetitors: "Kelola kompetitor",
  gapMissing: "Hilang",
  gapMissingDesc: "Kompetitor peringkat, Anda tidak — peluang konten baru.",
  gapWeak: "Lemah",
  gapWeakDesc: "Keduanya peringkat, kompetitor lebih tinggi.",
  gapStrong: "Kuat",
  gapStrongDesc: "Keduanya peringkat, Anda lebih tinggi atau setara.",
  gapShared: "Bersama",
  gapSharedDesc: "Semua kata kunci yang diperingkat keduanya.",
  ownPosition: "Posisi Anda",
  competitorPosition: "Posisi kompetitor",

  // ── Peringkat ──────────────────────────────────────────────
  rankSubtitle: "Pelacak posisi harian kata kunci di Google",
  visibility: "Visibilitas",
  visibilityHint: "Rata-rata CTR ekspektasi dari posisi tiap kata kunci (posisi 1 ≈ 28 %, 10 ≈ 2,5 %, tidak terindeks = 0). Semakin tinggi semakin baik.",
  avgPositionHint: "Rata-rata posisi kata kunci yang masuk 100 besar. Lebih rendah lebih baik.",
  top3: "Top 3",
  top10: "Top 10",
  top3Hint: "Jumlah kata kunci di posisi 1–3.",
  top10Hint: "Jumlah kata kunci di posisi 1–10.",
  trackedKeywords: "Kata kunci dilacak",
  ranked: "Terindeks (≤100)",
  unranked: "Tidak terindeks",
  improved: "Naik",
  declinedKw: "Turun",
  visibilityChart: "Tren visibilitas",
  visibilityChartDesc: "Visibilitas harian vs periode sebelumnya",
  positionChartDesc: "Posisi rata-rata harian — lebih rendah lebih baik",
  distributionTitle: "Distribusi posisi",
  distributionDesc: "Jumlah kata kunci per rentang posisi (snapshot terakhir)",
  sovTitle: "Share of voice",
  sovDesc: "Bobot kemunculan domain di 10 besar (dibobot CTR ekspektasi) untuk semua kata kunci yang dilacak",
  keywordsTable: "Kata kunci",
  keywordsTableDesc: "Posisi terkini, perubahan sejak awal periode, dan riwayat 30 hari",
  device: "Perangkat",
  tags: "Tag",
  allTags: "Semua tag",
  noTag: "Tanpa tag",
  positionCol: "Posisi",
  deltaCol: "Δ periode",
  deltaColHint: "Perubahan posisi vs snapshot pertama dalam periode. Positif = naik peringkat.",
  bestCol: "Terbaik",
  urlCol: "URL",
  history30: "30 hari",
  history30Hint: "Skor posisi (101 − posisi) 30 hari terakhir: naik = membaik.",
  addKeywords: "Tambah kata kunci",
  addKeywordsDesc: "Satu kata kunci per baris. Volume, KD & intent diambil otomatis; posisi pertama dicek langsung.",
  keywordsTextarea: "Kata kunci",
  keywordsPlaceholder: "kopi susu gula aren\nkedai kopi jakarta\n…",
  tagsLabel: "Tag (pisahkan dengan koma)",
  tagsPlaceholder: "brand, produk",
  keywordsAdded: "kata kunci ditambahkan",
  keywordsInvalid: "Masukkan minimal satu kata kunci (maks. 100 per tambah).",
  deleteKeyword: "Hapus kata kunci",
  keywordDeleted: "Kata kunci dihapus",
  editTags: "Ubah tag",
  tagsSaved: "Tag disimpan",
  ranksRefreshed: "Posisi diperbarui",
  noKeywordsTitle: "Belum ada kata kunci dilacak",
  noKeywordsDesc: "Tambahkan kata kunci untuk mulai melacak posisi harian, atau pilih dari hasil Riset Kata Kunci.",
  bucketUnranked: "Tidak terindeks",
  others: "Lainnya",
  positionUnit: "posisi",

  // ── Backlink ───────────────────────────────────────────────
  backlinksSubtitle: "Profil tautan balik: jumlah, domain perujuk, kualitas & tautan hilang",
  backlinksKpi: "Backlink",
  referringDomains: "Domain perujuk",
  domainRank: "Domain Rank",
  domainRankHint: "Skor otoritas domain 0–100 berdasarkan profil backlink (semakin tinggi semakin kuat).",
  dofollowShare: "Pangsa dofollow",
  dofollowShareHint: "Persentase backlink dofollow (meneruskan otoritas) dari total backlink.",
  vs30d: "vs 30 hari lalu",
  newLast30: "Baru (30 hr)",
  lostLast30: "Hilang (30 hr)",
  toxicShare: "Pangsa toxic",
  toxicShareHint: "Persentase tautan hidup dengan spam score ≥ 60.",
  refDomainsChart: "Domain perujuk",
  refDomainsChartDesc: "Jumlah domain perujuk harian",
  newLostChart: "Baru vs hilang",
  newLostChartDesc: "Backlink baru & hilang per minggu",
  newBacklinks: "Baru",
  lostBacklinks: "Hilang",
  tabAll: "Semua",
  tabNew: "Baru",
  tabLost: "Hilang",
  tabToxic: "Toxic",
  tabNewDesc: "Pertama terlihat dalam 30 hari terakhir.",
  tabLostDesc: "Tautan yang tidak lagi ditemukan pada crawl terakhir.",
  tabToxicDesc: "Spam score ≥ 60 — pertimbangkan disavow.",
  sourceUrl: "Sumber",
  anchor: "Anchor",
  dr: "DR",
  follow: "Follow",
  dofollow: "dofollow",
  nofollow: "nofollow",
  firstSeen: "Pertama",
  lastSeen: "Terakhir",
  spamScore: "Spam",
  target: "Target",
  topAnchors: "Anchor teratas",
  topAnchorsDesc: "Teks anchor yang paling sering dipakai (tautan hidup)",
  topRefDomains: "Domain perujuk teratas",
  topRefDomainsDesc: "Domain dengan tautan hidup terbanyak",
  backlinksRefreshed: "Data backlink diperbarui",
  noBacklinksTitle: "Belum ada data backlink",
  noBacklinksDesc: "Klik “Perbarui” untuk menarik ringkasan & daftar backlink pertama.",
  searchBacklink: "Cari domain/anchor…",

  // ── Kompetitor domain ──────────────────────────────────────
  competitorsSubtitle: "Benchmark domain Anda vs kompetitor: kata kunci organik, trafik, backlink",
  addDomain: "Tambah domain",
  addDomainDesc: "Masukkan domain kompetitor (tanpa https:// dan path). Maksimal 5 domain.",
  domainLabel: "Domain",
  domainPlaceholder: "kopikenangan.com",
  domainInvalid: "Format domain tidak valid.",
  domainExists: "Domain sudah ada.",
  domainMax: "Maksimal 5 kompetitor domain.",
  domainAdded: "Kompetitor ditambahkan",
  domainRemoved: "Kompetitor dihapus",
  removeDomain: "Hapus domain",
  yourDomain: "Domain Anda",
  benchmarkTitle: "Benchmark",
  benchmarkDesc: "Snapshot terakhir per domain",
  organicKeywords: "Kata kunci organik",
  organicTraffic: "Trafik organik",
  organicTrafficHint: "Perkiraan kunjungan organik per bulan.",
  trafficChart: "Tren trafik organik",
  trafficChartDesc: "Trafik organik harian per domain (domain Anda + 3 kompetitor teratas)",
  suggestedTitle: "Kompetitor yang disarankan",
  suggestedDesc: "Domain lain yang bersaing pada kata kunci yang sama",
  intersections: "Kata kunci beririsan",
  addSuggested: "Tambah",
  gapLink: "Lihat kesenjangan kata kunci",
  domainsRefreshed: "Snapshot domain diperbarui",
  noCompetitorsTitle: "Belum ada kompetitor domain",
  noCompetitorsDesc: "Tambahkan hingga 5 domain kompetitor untuk membandingkan kata kunci organik, trafik, dan backlink.",
  competitorsCount: "Kompetitor",

  // ── Audit (tambahan) ───────────────────────────────────────
  auditSchedule: "Jadwal audit",
  cadenceNone: "Tidak",
  cadenceWeekly: "Mingguan",
  cadenceDaily: "Harian",
  cadenceSaved: "Jadwal audit disimpan",
  issueTrend: "Tren isu",
  issueTrendDesc: "Jumlah isu per crawl menurut tingkat",
  errorsLabel: "Error",

  // ── Notifikasi ─────────────────────────────────────────────
  notifRankDropTitle: "Peringkat turun",
  notifRankDropBody: (n: number, sample: string) => `${n} kata kunci turun tajam sejak kemarin: ${sample}`,
  notifBacklinkLostTitle: "Backlink hilang",
  notifBacklinkLostBody: (n: number) => `${n} backlink hilang dalam sehari terakhir.`,
} as const;
