/**
 * Extra UI strings for the clients feature (portfolio, klien list, pengaturan klien).
 * Kept out of src/i18n/id.ts so parallel modules don't collide — same convention:
 * Bahasa Indonesia copy, English identifiers.
 */
export const tc = {
  portfolio: {
    search: "Cari klien…",
    sort: "Urutkan",
    sortName: "Nama",
    sortFollowers: "Followers",
    sortClicks: "Klik organik",
    sortSpend: "Belanja iklan",
    sortHealth: "Skor kesehatan",
    noMatch: "Tidak ada klien yang cocok dengan pencarian.",
    followersHint: "Total followers akun sendiri (IG, FB, TikTok) semua klien. Delta = pertumbuhan periode ini vs periode sebelumnya.",
    clicksHint: "Total klik organik Google Search Console semua klien.",
    spendHint: "Total belanja iklan Meta semua klien (agregat level iklan).",
    healthHint: "Rata-rata skor kesehatan situs dari audit terakhir tiap klien (0–100).",
    healthOutOf: "dari 100",
    noAudit: "Belum ada audit",
    scoreLabel: "Skor",
    moduleSocial: "Social",
    moduleSeo: "SEO",
    moduleAds: "Ads",
    noModules: "Belum ada modul aktif",
    lastSync: "Sinkron terakhir",
    metricFollowers: "Followers",
    metricClicks: "Klik organik",
    metricSpend: "Belanja iklan",
  },
  wizard: {
    eyebrow: "Konfigurasi awal",
    title: "Buat project baru",
    subtitle: "Lima langkah singkat. Bisa ditinggal kapan saja — yang sudah diisi tersimpan.",
    stepOf: "Langkah",
    upNext: "Berikutnya",
    back: "Kembali",
    next: "Lanjut",
    skip: "Lewati langkah ini",
    finish: "Selesaikan",
    saving: "Menyimpan…",
    pickOneChannel: "Pilih minimal satu jenis project.",
    selectAll: "Pilih semua",
    websiteForSeo: "Dipakai sebagai properti Search Console dan target audit.",
    // step 2
    channelsTitle: "Kanal yang dipantau",
    channelsHint: "Bisa diubah kapan saja di Pengaturan Klien. Pilihan ini juga jadi default tab pada tautan klien.",
    typesRecap: "Jenis project",
    socialLabel: "Social Media",
    socialDesc: "Instagram, Facebook, dan TikTok — analitik, kalender konten, penjadwalan & persetujuan post.",
    seoLabel: "SEO",
    seoDesc: "Search Console & GA4, riset kata kunci, rank tracker, backlink, kompetitor, dan audit situs.",
    adsLabel: "Meta Ads",
    adsDesc: "Belanja, hasil, biaya per hasil — dari Meta Marketing API atau impor CSV.",
    // step 3
    sourcesHint:
      "Hubungkan akun untuk data nyata, atau lewati dulu — dashboard tetap bisa dibuka dengan data demo.",
    noSourceYet: "Belum ada sumber data",
    setupNeededTitle: "Kredensial aplikasi belum diatur",
    setupNeededDesc: "Koneksi nyata butuh App ID Meta / Client ID Google. Sementara itu tombol “Simulasikan” mengisi data demo.",
    setupOpen: "Buka Setup awal",
    // step 4
    accessHint: "Anggota bisa ditambahkan belakangan. Tautan klien bersifat read-only.",
    // step 5
    doneTitle: "Klien siap dipakai",
    doneSubtitle: "Konfigurasi tersimpan. Berikut ringkasannya.",
    doneOpen: "Buka dashboard",
    doneReport: "Buat laporan pertama",
    summaryChannels: "Kanal",
    summarySources: "Sumber data",
    summaryShare: "Tautan klien",
    shareOn: "Aktif",
    shareOff: "Nonaktif",
    sourcesCount: (n: number) => `${n} sumber terdaftar`,
  },
  form: {
    nameRequired: "Nama klien wajib diisi",
    slugRequired: "Slug wajib diisi",
    slugInvalid: "Slug hanya boleh huruf kecil, angka, dan tanda hubung",
    slugHint: "Dipakai di URL, contoh: /clients/kopi-nusantara",
    websiteInvalid: "URL website tidak valid (awali dengan https://)",
    websitePlaceholder: "https://contoh.co.id",
    industryPlaceholder: "F&B, properti, hospitality…",
    descriptionPlaceholder: "Catatan singkat tentang klien…",
  },
  clients: {
    missing: "Klien tidak ditemukan atau sudah dihapus.",
    deleteTitle: "Hapus klien",
    typeToConfirm: (slug: string) => `Ketik “${slug}” untuk konfirmasi.`,
    confirmPlaceholder: "Tulis slug klien",
    confirmMismatch: "Slug tidak cocok",
  },
  settings: {
    profileDesc: "Identitas klien yang tampil di dashboard dan laporan.",
    accountId: "ID akun",
    simulate: "Simulasikan koneksi (demo)",
    simulated: "Koneksi demo berhasil dibuat",
    disconnected: "Koneksi diputus",
    disconnectConfirm: "Putuskan koneksi ini? Sinkronisasi otomatis akan berhenti sampai dihubungkan kembali.",
    connectedMeta: "Meta berhasil dihubungkan.",
    connectedGoogle: "Google berhasil dihubungkan.",
    demoNotice: "Kredensial penyedia belum dikonfigurasi — koneksi nyata tidak tersedia. Gunakan tombol simulasi (demo).",
    oauthDenied: "Akses ditolak di halaman izin penyedia.",
    oauthState: "Sesi OAuth tidak valid atau kedaluwarsa. Silakan coba lagi.",
    username: "Username",
    displayName: "Nama tampilan",
    ga4PropertyId: "ID properti GA4",
    ga4Placeholder: "cth. 3210001 (opsional)",
    adAccountExternalId: "ID akun iklan",
    adAccountPlaceholder: "act_1234567890",
    adAccountName: "Nama akun",
    addSocial: "Tambah akun",
    addSeo: "Tambah properti",
    addAds: "Tambah akun iklan",
    removeConfirm: "Hapus item ini? Data historis yang terkait ikut terhapus.",
    duplicate: "Sudah terdaftar untuk klien ini",
    resourceAdded: "Berhasil ditambahkan",
    resourceRemoved: "Dihapus",
    memberAdded: "Anggota ditambahkan",
    memberRemoved: "Anggota dihapus",
    memberRoleUpdated: "Peran anggota diperbarui",
    pickUser: "Pilih user…",
    noCandidates: "Semua user sudah menjadi anggota.",
    membersEmpty: "Belum ada anggota.",
    memberSince: "Bergabung",
    pinSet: "PIN terpasang",
    pinPlaceholder: "6 digit angka",
    pinInvalid: "PIN harus 6 digit angka",
    pinRemoveHint: "Kosongkan kolom PIN lalu simpan untuk menghapus PIN.",
    modulesMin: "Pilih minimal satu modul",
    shareDisabledHint: "Aktifkan untuk membagikan dashboard read-only ke klien.",
    dangerConfirmDesc: "Semua data klien — akun sosial, metrik SEO, data iklan, laporan — akan dihapus permanen.",
    readOnly: "Hanya manajer atau admin yang dapat mengubah bagian ini.",
    empty: "Belum ada",
  },
} as const;
