/**
 * NEW UI strings for the Reports/Share feature (Bahasa Indonesia).
 * Existing copy stays in src/i18n/id.ts (t.reports / t.share) — do not duplicate it here.
 */
export const rs = {
  builder: {
    periodHint: "Periode laporan mengikuti filter tanggal global di kanan atas.",
    titlePlaceholder: "Contoh: Laporan Agustus — Kopi Nusantara",
    previewTitle: "Pratinjau isi laporan",
    previewDesc: "Cuplikan KPI per modul untuk periode terpilih — persis seperti yang akan masuk ke PDF.",
    previewInsight: "Ringkasan strategis terakhir (periode ini)",
    noModules: "Pilih minimal satu modul.",
    titleRequired: "Judul laporan wajib diisi.",
    invalidRange: "Periode laporan tidak valid.",
    langId: "Bahasa Indonesia",
    langEn: "English",
    aiNote: "Ringkasan strategis dibuat otomatis dari data periode terpilih.",
  },
  history: {
    createdAt: "Dibuat pada",
    modules: "Modul",
    deleted: "Laporan dihapus",
    deleteTitle: "Hapus laporan?",
    period: "Periode",
  },
  insight: {
    overviewCard: "Lintas kanal",
    overviewDesc: "Narasi funnel: jangkauan → trafik → konversi",
    socialCard: "Social Media",
    socialDesc: "Followers, engagement, dan pola konten",
    seoCard: "SEO",
    seoDesc: "Klik organik, posisi, dan peluang kata kunci",
    adsCard: "Meta Ads",
    adsDesc: "Efisiensi belanja dan alokasi anggaran",
    generated: "Analisa berhasil dibuat",
    forRange: "untuk periode",
  },
  share: {
    statusTitle: "Status link klien",
    statusDesc: "Ringkasan pengaturan dashboard publik. Ubah lewat Pengaturan Klien.",
    active: "Link aktif",
    inactive: "Link nonaktif",
    pinSet: "PIN terpasang",
    pinNone: "Tanpa PIN",
    modulesShown: "Modul yang ditampilkan",
    changeSettings: "Ubah pengaturan",
    urlCopied: "URL tersalin",
    openInNewTab: "Buka di tab baru",
    pinPlaceholder: "••••••",
    presetLabel: "Rentang",
    preset7d: "7 hari",
    preset28d: "28 hari",
    preset90d: "90 hari",
    topPosts: "Postingan teratas",
    topQueries: "Kata kunci teratas",
    campaigns: "Kampanye",
    followerTotal: "Total followers (harian)",
  },
} as const;

/** Report PDF labels — id/en per Report.language. Section headings only; data is preformatted. */
export const pdfLabels = {
  id: {
    report: "Laporan Performa",
    preparedFor: "Disiapkan untuk",
    period: "Periode laporan",
    generatedOn: "Dibuat pada",
    vsPrevious: "vs periode sebelumnya",
    executiveSummary: "Ringkasan strategis",
    social: "Social Media",
    seo: "SEO",
    ads: "Meta Ads",
    dailyFollowers: "Pertumbuhan followers per hari (net)",
    perDay: "/hari",
    dailyClicks: "Klik organik per hari",
    dailySpend: "Belanja iklan per hari",
    topPosts: "Postingan teratas",
    topQueries: "Kata kunci teratas",
    campaigns: "Ringkasan kampanye",
    rankTitle: "Pelacak peringkat",
    rankVisibility: "Visibilitas",
    rankAvgPosition: "Posisi rata-rata terlacak",
    rankTop3: "Kata kunci di 3 besar",
    rankTop10: "Kata kunci di 10 besar",
    rankTable: "10 kata kunci terlacak dengan posisi terbaik",
    rankUp: "Naik",
    rankDown: "Turun",
    rankFlat: "Tetap",
    rankNew: "Baru masuk",
    rankLost: "Keluar 100 besar",
    rankUnranked: "Di luar 100",
    colKeyword: "Kata kunci",
    colPosition: "Posisi",
    colChange: "Perubahan periode ini",
    colVolume: "Volume / bulan",
    backlinksTitle: "Backlink",
    backlinksTotal: "Total backlink",
    referringDomains: "Domain perujuk",
    domainRank: "Domain rank",
    dofollowShare: "Porsi dofollow",
    backlinksNew: "Backlink baru periode ini",
    backlinksLost: "Backlink hilang periode ini",
    publishingTitle: "Performa publikasi",
    publishedPosts: "Postingan terbit",
    publishedOn: "Terbit di",
    publishFailed: "Gagal terbit",
    publishedTop: "5 postingan terbit dengan interaksi tertinggi",
    publishedRecent: "5 postingan terbit terbaru",
    colPost: "Postingan",
    colPublishedAt: "Tanggal terbit",
    colEngagements: "Interaksi",
    closing: "Terima kasih",
    closingBody: "Kami senang bekerja sama dan berharap dapat mencapai hasil yang lebih baik bersama.",
    footer: "Dibuat oleh WHITE Analytics",
    page: "Halaman",
  },
  en: {
    report: "Performance Report",
    preparedFor: "Prepared for",
    period: "Reporting period",
    generatedOn: "Generated on",
    vsPrevious: "vs previous period",
    executiveSummary: "Strategic summary",
    social: "Social Media",
    seo: "SEO",
    ads: "Meta Ads",
    dailyFollowers: "Daily net follower growth",
    perDay: "/day",
    dailyClicks: "Daily organic clicks",
    dailySpend: "Daily ad spend",
    topPosts: "Top posts",
    topQueries: "Top queries",
    campaigns: "Campaign summary",
    rankTitle: "Rank tracker",
    rankVisibility: "Visibility",
    rankAvgPosition: "Average tracked position",
    rankTop3: "Keywords in top 3",
    rankTop10: "Keywords in top 10",
    rankTable: "10 best-ranking tracked keywords",
    rankUp: "Up",
    rankDown: "Down",
    rankFlat: "No change",
    rankNew: "New entry",
    rankLost: "Left top 100",
    rankUnranked: "Outside 100",
    colKeyword: "Keyword",
    colPosition: "Position",
    colChange: "Change this period",
    colVolume: "Volume / month",
    backlinksTitle: "Backlinks",
    backlinksTotal: "Total backlinks",
    referringDomains: "Referring domains",
    domainRank: "Domain rank",
    dofollowShare: "Dofollow share",
    backlinksNew: "New backlinks this period",
    backlinksLost: "Lost backlinks this period",
    publishingTitle: "Publishing performance",
    publishedPosts: "Posts published",
    publishedOn: "Published on",
    publishFailed: "Failed to publish",
    publishedTop: "Top 5 published posts by engagement",
    publishedRecent: "5 most recent published posts",
    colPost: "Post",
    colPublishedAt: "Published",
    colEngagements: "Engagements",
    closing: "Thank you",
    closingBody: "We enjoy working together and look forward to achieving even better results.",
    footer: "Generated by WHITE Analytics",
    page: "Page",
  },
} as const;

export type PdfLang = keyof typeof pdfLabels;
