/** Setup wizard — UI strings (Bahasa Indonesia). */
export const ts = {
  eyebrow: "Setup awal",
  title: "Setup awal & integrasi",
  subtitle: "Sekali untuk seluruh ruang kerja. Semua langkah boleh dilewati — tanpa kredensial, dashboard tetap berjalan dengan data demo.",
  stepOf: "Langkah",
  next: "Lanjut",
  back: "Kembali",
  skipAll: "Lewati, atur nanti",
  finish: "Selesai & buat project pertama",
  toPortfolio: "Ke portofolio",
  save: "Simpan",
  saveVerify: "Simpan & uji koneksi",
  verifying: "Menguji…",
  clear: "Hapus kredensial",
  clearConfirm: "Hapus kredensial ini dari aplikasi? Adapter kembali ke mode demo (atau ke nilai .env bila ada).",
  saved: "Kredensial tersimpan.",
  cleared: "Kredensial dihapus.",
  sourceDb: "Disimpan di aplikasi",
  sourceEnv: "Dari .env server",
  sourceNone: "Belum diatur",
  verifiedAt: "Diuji",
  neverVerified: "Belum diuji",
  modeReal: "Data nyata",
  modeDemo: "Mode demo",
  secretKept: "Kosongkan untuk mempertahankan secret yang tersimpan.",
  optionalWord: "opsional",
  redirectUri: "Redirect URI OAuth",
  copy: "Salin",
  copied: "Tersalin",
  openDocs: "Buka dokumentasi",

  // Meta
  metaAppId: "App ID",
  metaAppSecret: "App Secret",
  metaWhere: "Meta for Developers → aplikasi Anda → App settings → Basic.",
  metaRedirectHint: "Tempel di Facebook Login → Settings → Valid OAuth Redirect URIs.",
  reviewTitle: "Checklist App Review",
  reviewDesc:
    "Tanpa Advanced Access pada izin di bawah, aplikasi hanya bisa membaca akun tim Anda sendiri dan tidak bisa menerbitkan post. Proses review Meta biasanya 1–3 minggu; catat progresnya di sini.",
  reviewProgress: (a: number, t: number) => `${a}/${t} izin wajib disetujui`,
  permission: "Izin",
  unlocks: "Membuka",
  status: "Status",
  unlockSocial: "Analitik social",
  unlockPublish: "Publikasi post",
  unlockAds: "Meta Ads",
  unlockEngagement: "Inbox (Fase C)",
  optional: "opsional",
  statusNotRequested: "Belum diajukan",
  statusSubmitted: "Diajukan",
  statusApproved: "Disetujui",
  appLive: "Aplikasi sudah dalam mode Live",
  businessVerified: "Business Verification selesai",
  publishReady: "Publikasi Instagram & Facebook siap dikirim sungguhan.",
  publishNotReady: "Publikasi masih berjalan lewat simulasi sampai izin publikasi disetujui dan aplikasi Live.",
  reviewSaved: "Checklist diperbarui.",
  tiktokTitle: "TikTok",
  tiktokDesc:
    "Analitik TikTok memakai data demo. Publikasi ke TikTok belum tersedia — butuh persetujuan TikTok Content Posting API; menu komposer tetap menerima akun TikTok tetapi pengiriman akan ditolak dengan pesan jelas.",

  // Google
  googleClientId: "Client ID",
  googleClientSecret: "Client Secret",
  googleWhere: "Google Cloud Console → APIs & Services → Credentials → OAuth 2.0 Client (Web). Aktifkan Search Console API dan Google Analytics Data API.",
  googleRedirectHint: "Tambahkan ke Authorized redirect URIs pada OAuth client.",

  // DataForSEO
  dfsLogin: "Login (email akun)",
  dfsPassword: "API password",
  dfsWhere: "app.dataforseo.com → API Access. Akun baru mendapat kredit uji; setelah itu bayar per panggilan tanpa langganan.",
  costTitle: "Estimasi biaya bulanan",
  costDesc: "Perkiraan dari daftar harga publik untuk job harian (SERP tiap kata kunci, ringkasan backlink, overview domain) plus riset ad-hoc. Cek harga terbaru di dataforseo.com/pricing sebelum menganggarkan.",
  costKeywords: "Kata kunci dilacak (semua klien)",
  costCompetitors: "Domain kompetitor (semua klien)",
  costResearch: "Riset kata kunci / bulan",
  costRate: "Kurs USD → IDR",
  costAdvanced: "Harga satuan (USD)",
  priceSerp: "SERP per kata kunci per hari",
  priceBacklinks: "Ringkasan backlink per hari",
  priceDomain: "Overview domain per domain per hari",
  priceResearch: "Riset per sesi",
  costRank: "Rank tracker",
  costBacklinks: "Backlink",
  costDomains: "Domain kompetitor",
  costResearchRow: "Riset",
  costTotal: "Total / bulan",
  perMonth: "/bulan",

  // Apify
  apifyToken: "API token",
  apifyActors: "Override actor (JSON, opsional)",
  apifyWhere: "console.apify.com → Settings → Integrations → Personal API tokens. Free tier memberi kredit bulanan; selebihnya bayar per hasil.",
  apifyReplaces: "Yang ditangani Apify",
  apifySerp: "Posisi SERP harian untuk rank tracker (menggantikan DataForSEO bila DataForSEO kosong). Volume, KD, dan backlink tetap butuh DataForSEO.",
  apifySocial: "Followers, jumlah post, dan engagement post publik untuk akun klien & kompetitor di Instagram, TikTok, Facebook — tanpa App Review Meta. Reach/impressions tetap butuh Meta Insights.",
  apifyTiktok: "TikTok analitik jadi nyata (profil & video publik). Publikasi ke TikTok tetap belum tersedia.",
  apifyPriority: "Bila DataForSEO dan Apify keduanya terisi, SERP memakai DataForSEO; bila Meta terhubung untuk sebuah klien, insight Meta tetap dipakai dan Apify melengkapi data publik.",
  apifyCostTitle: "Estimasi biaya bulanan (Apify)",
  apifyCostDesc: "Perkiraan harga per hasil dari Apify Store (SERP ±$3,5/1000 query; Instagram ±$2,3/1000 hasil). Cek harga actor di apify.com/store.",
  apifyAccounts: "Akun social disinkronkan harian (klien + kompetitor)",
  apifyPosts: "Post per akun per sinkronisasi",
  apifyCostSerp: "SERP",
  apifyCostSocial: "Social",
  apifyUsage: (used: string, limit: string) => `Pemakaian bulan ini ${used} dari ${limit}`,

  // AI
  aiKey: "API key",
  aiModel: "Model",
  aiWhere: "openrouter.ai → Keys. Model default: anthropic/claude-sonnet-4.5.",

  // Done
  doneTitle: "Ruang kerja siap",
  doneDesc: "Mode tiap integrasi saat ini. Semuanya bisa diubah kapan saja dari menu Admin → Setup awal & integrasi.",
  doneNext: "Langkah berikutnya: buat project pertama — jenis project menentukan sumber data yang diminta.",
  integration: "Integrasi",
  mode: "Mode",
  labelMeta: "Meta",
  labelGoogle: "Google",
  labelDfs: "DataForSEO",
  labelAi: "OpenRouter",
  labelApify: "Apify",
  apifyMode: "SERP + data publik social",
  labelTiktok: "TikTok",
  tiktokMode: "Analitik demo · publikasi belum tersedia",
  publishMode: (ready: boolean) => (ready ? "Publikasi nyata" : "Publikasi simulasi"),
  finished: "Setup ditandai selesai.",
} as const;
